
import java.sql.*;
import javax.swing.JOptionPane;


public class Staff extends javax.swing.JFrame {

    Connection con;
    Statement stmt,stmt1;
    ResultSet rs,rs1;
    int id;
    String pass,name,query;
    public Staff() {
       initComponents();
        reset();
    
      try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vista","root","");
            stmt=con.createStatement();
            String query="SELECT * FROM LOGIN;";
            rs=stmt.executeQuery(query);
            rs.next();
            displayRecord();
            
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(this, ec);
        } 
    }
    public final void displayRecord(){
    try{    id=rs.getInt("USERID");
            name=rs.getString("USERNAME");
            pass=rs.getString("PASSWORD");
            idtxt.setText(""+id);
            ntxt.setText(""+name);
            ptxt.setText("*****");
            
    }
    catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(this,ec);
        }
    }

   public final void reset(){
        ftbtn.setEnabled(true);
        ltbtn.setEnabled(true);
        ntbtn.setEnabled(true);
        psbtn.setEnabled(true);
        Addbtn.setEnabled(false);
        updbtn.setEnabled(false);
        editbtn.setEnabled(true);
        cbtn.setEnabled(true);
        idtxt.setEditable(false);
        ntxt.setEditable(false);
        ptxt.setEditable(false);
        
    }
       public final void clear(){
       ntxt.setText("");
        ptxt.setText("");
        idtxt.setText("");
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
    @SuppressWarnings("unchecked")
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idtxt = new javax.swing.JTextField();
        ntxt = new javax.swing.JTextField();
        ptxt = new javax.swing.JTextField();
        cbtn = new javax.swing.JButton();
        updbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        psbtn = new javax.swing.JButton();
        ltbtn = new javax.swing.JButton();
        ftbtn = new javax.swing.JButton();
        ntbtn = new javax.swing.JButton();
        Addbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idtxt1 = new javax.swing.JTextField();
        ntxt1 = new javax.swing.JTextField();
        sbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        spwbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));
        getContentPane().add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 212, 30));
        getContentPane().add(ntxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 212, 30));
        getContentPane().add(ptxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 212, 30));

        cbtn.setText("Close");
        cbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtnActionPerformed(evt);
            }
        });
        getContentPane().add(cbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 91, 30));

        updbtn.setBackground(new java.awt.Color(102, 255, 102));
        updbtn.setText("UPDATE");
        updbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updbtnActionPerformed(evt);
            }
        });
        getContentPane().add(updbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 91, 30));

        editbtn.setText("Edit");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        getContentPane().add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 91, 30));

        psbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        psbtn.setText("Previous <");
        psbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psbtnActionPerformed(evt);
            }
        });
        getContentPane().add(psbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 30));

        ltbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ltbtn.setText("Last >>");
        ltbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ltbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ltbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 91, 30));

        ftbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ftbtn.setText("First <<");
        ftbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ftbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 91, 30));

        ntbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ntbtn.setText("Next >");
        ntbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ntbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 91, 30));

        Addbtn.setText("ADD");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 90, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 220, 140, 150));

        jLabel5.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel5.setText("STAFF INFORMATION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 420, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setText("User ID");

        jLabel8.setText("Username");

        sbtn.setText("Search");
        sbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnActionPerformed(evt);
            }
        });

        jButton1.setText("Reset");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Search for specific user");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ntxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idtxt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel6)))
                .addGap(68, 68, 68))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ntxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 370, 250));

        jLabel10.setText(" ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel11.setText("     ");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, -1, -1));

        spwbtn.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        spwbtn.setText("Show Password");
        spwbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spwbtnActionPerformed(evt);
            }
        });
        getContentPane().add(spwbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updbtnActionPerformed
        String naam= ntxt.getText(), pwd=ptxt.getText();
       int uid=Integer.parseInt(idtxt.getText());
        String query2;
        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vista","root","");
            stmt1=con.createStatement();

            int code=JOptionPane.showConfirmDialog(this,"Are you sure you want to update this information?","Confirm?",JOptionPane.YES_NO_OPTION);
            if(code==JOptionPane.YES_OPTION)
            {
                query2="UPDATE LOGIN SET USERID=" + uid + ", USERNAME='" + naam + "',PASSWORD='" + pwd + "' WHERE USERID=" + id +";";
                int ss=stmt1.executeUpdate(query2);
                if(ss>0) JOptionPane.showMessageDialog(this,"Updation Successful!!");
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(this,e);
        }

        try
        {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vista","root","");
            stmt=con.createStatement();
            String query="SELECT * FROM LOGIN;";
            rs=stmt.executeQuery(query);
            rs.next();
            displayRecord();
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(this, ec);
        }
    }//GEN-LAST:event_updbtnActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        updbtn.setEnabled(true);
        Addbtn.setEnabled(true);
        ftbtn.setEnabled(false);
        ltbtn.setEnabled(false);
        ntbtn.setEnabled(false);
        psbtn.setEnabled(false);
        try
        {
            id=rs.getInt("USERID");
        }
        catch(SQLException e) {
            JOptionPane.showMessageDialog(this, e);
        }
        ntxt.setEditable(true);
        idtxt.setEditable(true);
        ptxt.setEditable(true);
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void psbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psbtnActionPerformed
        reset();
        try {
            if (rs.previous()) {
                displayRecord();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"End of Results!!");
                rs.first();
            }
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(this, ec);
        }
    }//GEN-LAST:event_psbtnActionPerformed

    private void ltbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ltbtnActionPerformed
        reset();
        try
        {
            rs.last();
            displayRecord();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_ltbtnActionPerformed

    private void ftbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftbtnActionPerformed
        reset();
        try
        {
            rs.first();
            displayRecord();
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

    }//GEN-LAST:event_ftbtnActionPerformed

    private void ntbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntbtnActionPerformed
        reset();
        try {
            if (rs.next()) {
                displayRecord();
            }
            else
            {
                JOptionPane.showMessageDialog(this,"End of Results!!");
                rs.last();
            }
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(this, ec);
        }
    }//GEN-LAST:event_ntbtnActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        
            String nm=ntxt.getText(), pwd=ptxt.getText();
            String uid=idtxt.getText();
            String query1="SELECT * FROM LOGIN WHERE USERID=" + uid + ";";
            String query2;
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vista","root","");
                stmt1=con.createStatement();
                rs1=stmt1.executeQuery(query1);
                if(!(rs1.next()))
                {
                    int code=JOptionPane.showConfirmDialog(this,"Insert Record?","Confirm?",JOptionPane.YES_NO_OPTION);
                    if(code==JOptionPane.YES_OPTION)
                    {
                        query2="INSERT INTO LOGIN VALUES(" + uid + ",'" + nm + "','" + pwd + "');";
                        int ss=stmt1.executeUpdate(query2);
                        if(ss>0) JOptionPane.showMessageDialog(this,"Updation Successful!!");
                        else     JOptionPane.showMessageDialog(this,"User ID already exists");
                        clear();
                    }
                }
                else {JOptionPane.showMessageDialog(this,"User ID already exists");}
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(this,e);
            }
        
    }//GEN-LAST:event_AddbtnActionPerformed

    private void cbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cbtnActionPerformed

    private void sbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnActionPerformed
        String sname,sid;
       sname=ntxt1.getText();
        sid=idtxt1.getText();
       Statement stmt;
       String query1;
       query1="SELECT * FROM LOGIN WHERE USERID LIKE '%" + sid + "%' AND USERNAME LIKE '%" + sname + "%';"; 
       try
       {
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vista","root","");
           stmt=con.createStatement();
           rs=stmt.executeQuery(query1);
           if(rs.next()) displayRecord();
           else 
           {
               JOptionPane.showMessageDialog(this,"No Matching Records Found!!!");
               rs=stmt.executeQuery(query);
               rs.next();
               displayRecord();
           }
       }
       catch(SQLException ex){
       JOptionPane.showMessageDialog(this,ex);
       }
    }//GEN-LAST:event_sbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ntxt1.setText("");
        
        idtxt1.setText("");
        displayRecord();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spwbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spwbtnActionPerformed
        // TODO add your handling code here:
        try{
            pass=rs.getString("PASSWORD");
            ptxt.setText(""+pass);
        }
        catch(SQLException ec)
        {
            JOptionPane.showMessageDialog(this, ec);
        }

    }//GEN-LAST:event_spwbtnActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton cbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton ftbtn;
    private javax.swing.JTextField idtxt;
    private javax.swing.JTextField idtxt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ltbtn;
    private javax.swing.JButton ntbtn;
    private javax.swing.JTextField ntxt;
    private javax.swing.JTextField ntxt1;
    private javax.swing.JButton psbtn;
    private javax.swing.JTextField ptxt;
    private javax.swing.JButton sbtn;
    private javax.swing.JButton spwbtn;
    private javax.swing.JButton updbtn;
    // End of variables declaration//GEN-END:variables
}
